name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-crates-io:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Publish
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }}
