name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rustfmt:
    name: Formatting
    runs-on: ubuntu-22.04
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Check the formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check --verbose

  clippy:
    name: Lints
    runs-on: ubuntu-22.04
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: true
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Check the lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --lib --tests --bins --examples --verbose -- -D warnings

  build_and_test:
    name: Build and test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
